export const brands = [
  { id: "apple", name: "Apple", logo: "A" },
  { id: "samsung", name: "Samsung", logo: "S" },
  { id: "xiaomi", name: "Xiaomi", logo: "X" },
  { id: "oneplus", name: "OnePlus", logo: "O" },
  { id: "google", name: "Google", logo: "G" },
  { id: "oppo", name: "OPPO", logo: "O" },
  { id: "vivo", name: "Vivo", logo: "V" },
  { id: "nothing", name: "Nothing", logo: "N" },
];

export const categories = [
  { id: "flagship", name: "Flagship", image: "📱", count: 12 },
  { id: "midrange", name: "Mid-Range", image: "📲", count: 10 },
  { id: "budget", name: "Budget", image: "📞", count: 4 },
  { id: "foldable", name: "Foldable", image: "📂", count: 2 },
  { id: "gaming", name: "Gaming", image: "🎮", count: 12 },
];

export const products = [
  {
    id: 1,
    name: "iPhone 16 Pro Max",
    brand: "apple",
    category: "flagship",
    price: 1199,
    originalPrice: 1299,
    rating: 4.8,
    reviews: 342,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro-max.jpg",
    colors: ["#1a1a2e", "#e8e8e8", "#c9a96e"],
    storage: ["256GB", "512GB", "1TB"],
    badge: "Best Seller",
    inStock: true,
    description:
      "The most advanced iPhone ever. A18 Pro chip, 48MP camera system, and all-day battery life.",
    specs: {
      Display: '6.9" Super Retina XDR OLED',
      Processor: "A18 Pro Chip",
      RAM: "8GB",
      Battery: "4685mAh",
      Camera: "48MP Main + 12MP Ultra + 12MP Telephoto",
      OS: "iOS 19",
    },
  },
  {
    id: 2,
    name: "Samsung Galaxy S25 Ultra",
    brand: "samsung",
    category: "flagship",
    price: 1299,
    originalPrice: 1399,
    rating: 4.7,
    reviews: 528,
    image: "https://images.pexels.com/photos/969462/pexels-photo-969462.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop",
    colors: ["#1b263b", "#e0e1dd", "#d4a373"],
    storage: ["256GB", "512GB", "1TB"],
    badge: "New",
    inStock: true,
    description:
      "Galaxy AI is here. The ultimate Galaxy experience with S Pen, 200MP camera, and Snapdragon 8 Gen 4.",
    specs: {
      Display: '6.9" Dynamic AMOLED 2X',
      Processor: "Snapdragon 8 Gen 4",
      RAM: "12GB",
      Battery: "5000mAh",
      Camera: "200MP Main + 50MP Ultra + 50MP Telephoto + 10MP Telephoto",
      OS: "One UI 7 (Android 15)",
    },
  },
  {
    id: 3,
    name: "Xiaomi 15 Pro",
    brand: "xiaomi",
    category: "flagship",
    price: 899,
    originalPrice: 999,
    rating: 4.6,
    reviews: 234,
    image: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-15-pro.jpg",
    colors: ["#2d3436", "#dfe6e9", "#6c5ce7"],
    storage: ["256GB", "512GB"],
    badge: "Sale",
    inStock: true,
    description:
      "Leica optics, Snapdragon 8 Gen 4, and 120W HyperCharge.",
    specs: {
      Display: '6.73" LTPO AMOLED',
      Processor: "Snapdragon 8 Gen 4",
      RAM: "12GB",
      Battery: "5400mAh",
      Camera: "50MP Leica Main + 50MP Ultra + 50MP Telephoto",
      OS: "HyperOS 2 (Android 15)",
    },
  },
  {
    id: 4,
    name: "OnePlus 13",
    brand: "oneplus",
    category: "flagship",
    price: 799,
    originalPrice: 899,
    rating: 4.5,
    reviews: 187,
    image: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-13.jpg",
    colors: ["#2b2d42", "#edf2f4", "#8d99ae"],
    storage: ["256GB", "512GB"],
    badge: null,
    inStock: true,
    description: "Never Settle. Hasselblad camera system, 100W charging, and Fluid AMOLED display.",
    specs: {
      Display: '6.82" LTPO AMOLED',
      Processor: "Snapdragon 8 Gen 4",
      RAM: "12GB",
      Battery: "5000mAh",
      Camera: "50MP Hasselblad Main + 48MP Ultra + 64MP Telephoto",
      OS: "OxygenOS 15 (Android 15)",
    },
  },
  {
    id: 5,
    name: "Google Pixel 10 Pro",
    brand: "google",
    category: "flagship",
    price: 999,
    originalPrice: 1099,
    rating: 4.7,
    reviews: 156,
    image: "https://images.pexels.com/photos/13244697/pexels-photo-13244697.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop",
    colors: ["#f8f9fa", "#212529", "#52b788"],
    storage: ["128GB", "256GB", "512GB"],
    badge: null,
    inStock: true,
    description:
      "Google AI at your fingertips. Tensor G5 chip, incredible camera, and 7 years of updates.",
    specs: {
      Display: '6.7" LTPO OLED',
      Processor: "Google Tensor G5",
      RAM: "12GB",
      Battery: "4950mAh",
      Camera: "50MP Main + 48MP Ultra + 48MP Telephoto",
      OS: "Android 16",
    },
  },
  {
    id: 6,
    name: "Nothing Phone (3)",
    brand: "nothing",
    category: "midrange",
    price: 599,
    originalPrice: 699,
    rating: 4.3,
    reviews: 98,
    image: "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-3.jpg",
    colors: ["#ffffff", "#000000"],
    storage: ["128GB", "256GB"],
    badge: null,
    inStock: true,
    description:
      "Glyph Interface. Transparent design. Pure Android experience with a unique LED interface.",
    specs: {
      Display: '6.7" LTPO OLED',
      Processor: "Snapdragon 8 Gen 3",
      RAM: "8GB",
      Battery: "4700mAh",
      Camera: "50MP Main + 50MP Ultra",
      OS: "Nothing OS 3 (Android 15)",
    },
  },
  {
    id: 7,
    name: "iPhone 16",
    brand: "apple",
    category: "flagship",
    price: 899,
    originalPrice: 999,
    rating: 4.6,
    reviews: 412,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16.jpg",
    colors: ["#1a1a2e", "#e8e8e8", "#c9a96e", "#e63946"],
    storage: ["128GB", "256GB", "512GB"],
    badge: "Popular",
    inStock: true,
    description: "A18 chip, 48MP camera, Action button, and USB-C.",
    specs: {
      Display: '6.1" Super Retina XDR OLED',
      Processor: "A18 Chip",
      RAM: "8GB",
      Battery: "3561mAh",
      Camera: "48MP Main + 12MP Ultra",
      OS: "iOS 19",
    },
  },
  {
    id: 8,
    name: "Samsung Galaxy Z Fold 7",
    brand: "samsung",
    category: "foldable",
    price: 1899,
    originalPrice: 1999,
    rating: 4.4,
    reviews: 87,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold7.jpg",
    colors: ["#2d3436", "#dfe6e9"],
    storage: ["256GB", "512GB", "1TB"],
    badge: "Premium",
    inStock: false,
    description:
      "The future of smartphones. 7.6-inch main display, S Pen support, and multitasking reimagined.",
    specs: {
      Display: '7.6" Foldable Dynamic AMOLED + 6.3" Cover',
      Processor: "Snapdragon 8 Gen 4",
      RAM: "12GB",
      Battery: "4400mAh",
      Camera: "50MP Main + 12MP Ultra + 10MP Telephoto",
      OS: "One UI 7 (Android 15)",
    },
  },
  {
    id: 9,
    name: "OPPO Find X8 Pro",
    brand: "oppo",
    category: "flagship",
    price: 1099,
    originalPrice: 1199,
    rating: 4.5,
    reviews: 134,
    image: "https://fdn2.gsmarena.com/vv/bigpic/oppo-find-x8-pro.jpg",
    colors: ["#1e1e2f", "#f5f5f5", "#c0a080"],
    storage: ["256GB", "512GB"],
    badge: null,
    inStock: true,
    description:
      "Hasselblad Portrait Master. MediaTek Dimensity 9400, 80W SuperVOOC charging.",
    specs: {
      Display: '6.78" LTPO AMOLED',
      Processor: "MediaTek Dimensity 9400",
      RAM: "16GB",
      Battery: "5000mAh",
      Camera: "50MP Main + 50MP Ultra + 50MP Telephoto + 50MP Telephoto",
      OS: "ColorOS 15 (Android 15)",
    },
  },
  {
    id: 10,
    name: "Vivo X200 Pro",
    brand: "vivo",
    category: "flagship",
    price: 949,
    originalPrice: 1049,
    rating: 4.4,
    reviews: 112,
    image: "https://fdn2.gsmarena.com/vv/bigpic/vivo-x200-pro.jpg",
    colors: ["#1a1a2e", "#f0f0f0", "#4a4a6a"],
    storage: ["256GB", "512GB"],
    badge: null,
    inStock: true,
    description:
      "ZEISS optics, 200MP telephoto, and Dimensity 9400. Professional photography in your pocket.",
    specs: {
      Display: '6.78" LTPO AMOLED',
      Processor: "MediaTek Dimensity 9400",
      RAM: "12GB",
      Battery: "5400mAh",
      Camera: "50MP Main + 50MP Ultra + 200MP Telephoto",
      OS: "Funtouch OS 15 (Android 15)",
    },
  },
  {
    id: 11,
    name: "Samsung Galaxy A56",
    brand: "samsung",
    category: "midrange",
    price: 449,
    originalPrice: 499,
    rating: 4.3,
    reviews: 278,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a56-r.jpg",
    colors: ["#2d3436", "#dfe6e9", "#6c5ce7", "#e17055"],
    storage: ["128GB", "256GB"],
    badge: "Best Value",
    inStock: true,
    description:
      "Awesome screen, awesome camera, awesome battery. Galaxy AI features at a mid-range price.",
    specs: {
      Display: '6.6" Super AMOLED 120Hz',
      Processor: "Exynos 1580",
      RAM: "8GB",
      Battery: "5000mAh",
      Camera: "50MP Main + 12MP Ultra + 5MP Macro",
      OS: "One UI 7 (Android 15)",
    },
  },
  {
    id: 12,
    name: "Redmi Note 15 Pro",
    brand: "xiaomi",
    category: "midrange",
    price: 349,
    originalPrice: 399,
    rating: 4.2,
    reviews: 567,
    image: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-15-pro-5g.jpg",
    colors: ["#2b2d42", "#edf2f4", "#e63946"],
    storage: ["128GB", "256GB"],
    badge: "Most Popular",
    inStock: true,
    description:
      "200MP camera, 120W fast charging, and AMOLED display at an unbeatable price.",
    specs: {
      Display: '6.67" AMOLED 120Hz',
      Processor: "Snapdragon 7s Gen 3",
      RAM: "8GB",
      Battery: "5000mAh",
      Camera: "200MP Main + 8MP Ultra + 2MP Macro",
      OS: "HyperOS 2 (Android 15)",
    },
  },
  {
    id: 13,
    name: "OnePlus Nord 5",
    brand: "oneplus",
    category: "midrange",
    price: 499,
    originalPrice: 549,
    rating: 4.1,
    reviews: 203,
    image: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord5.jpg",
    colors: ["#1e1e2f", "#f5f5f5"],
    storage: ["128GB", "256GB"],
    badge: null,
    inStock: true,
    description: "Flagship performance at a mid-range price. Snapdragon 8 Gen 3, 100W charging.",
    specs: {
      Display: '6.74" AMOLED 120Hz',
      Processor: "Snapdragon 8 Gen 3",
      RAM: "12GB",
      Battery: "5000mAh",
      Camera: "50MP Main + 8MP Ultra + 2MP Macro",
      OS: "OxygenOS 15 (Android 15)",
    },
  },
  {
    id: 14,
    name: "Google Pixel 10a",
    brand: "google",
    category: "budget",
    price: 499,
    originalPrice: 549,
    rating: 4.3,
    reviews: 145,
    image: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-10a.jpg",
    colors: ["#f8f9fa", "#212529", "#ade8f4"],
    storage: ["128GB", "256GB"],
    badge: null,
    inStock: true,
    description: "Google AI, Tensor G5, and incredible camera at a more accessible price.",
    specs: {
      Display: '6.3" OLED 120Hz',
      Processor: "Google Tensor G5",
      RAM: "8GB",
      Battery: "4700mAh",
      Camera: "50MP Main + 13MP Ultra",
      OS: "Android 16",
    },
  },
  {
    id: 15,
    name: "Samsung Galaxy M55",
    brand: "samsung",
    category: "budget",
    price: 299,
    originalPrice: 349,
    rating: 4.0,
    reviews: 432,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m55.jpg",
    colors: ["#2d3436", "#dfe6e9"],
    storage: ["128GB"],
    badge: "Budget Pick",
    inStock: true,
    description: "Massive 6000mAh battery, 120Hz Super AMOLED, and solid performance.",
    specs: {
      Display: '6.7" Super AMOLED 120Hz',
      Processor: "Exynos 1480",
      RAM: "8GB",
      Battery: "6000mAh",
      Camera: "50MP Main + 8MP Ultra + 2MP Macro",
      OS: "One UI 7 (Android 15)",
    },
  },
  {
    id: 16,
    name: "Nothing Phone (3a)",
    brand: "nothing",
    category: "midrange",
    price: 399,
    originalPrice: 449,
    rating: 4.1,
    reviews: 76,
    image: "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-3a.jpg",
    colors: ["#ffffff", "#000000"],
    storage: ["128GB", "256GB"],
    badge: null,
    inStock: true,
    description: "Essential Glyph Interface. Clean design, solid performance, unique LED interactions.",
    specs: {
      Display: '6.7" AMOLED 120Hz',
      Processor: "Snapdragon 7s Gen 3",
      RAM: "8GB",
      Battery: "5000mAh",
      Camera: "50MP Main + 8MP Ultra + 2MP Macro",
      OS: "Nothing OS 3 (Android 15)",
    },
  },
  {
    id: 17,
    name: "Samsung Galaxy S25",
    brand: "samsung",
    category: "flagship",
    price: 999,
    originalPrice: 1099,
    rating: 4.6,
    reviews: 312,
    image: "https://images.pexels.com/photos/4842577/pexels-photo-4842577.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop",
    colors: ["#1b263b", "#e0e1dd", "#6c5ce7"],
    storage: ["128GB", "256GB", "512GB"],
    badge: null,
    inStock: true,
    description:
      "Galaxy AI features at your fingertips. Powerful Snapdragon 8 Gen 4, stunning display, and pro-grade camera.",
    specs: {
      Display: '6.2" Dynamic AMOLED 120Hz',
      Processor: "Snapdragon 8 Gen 4",
      RAM: "8GB",
      Battery: "4000mAh",
      Camera: "50MP Main + 12MP Ultra + 10MP Telephoto",
      OS: "One UI 7 (Android 15)",
    },
  },
  {
    id: 18,
    name: "iPhone 16 Pro",
    brand: "apple",
    category: "flagship",
    price: 1099,
    originalPrice: 1199,
    rating: 4.7,
    reviews: 289,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro.jpg",
    colors: ["#1a1a2e", "#e8e8e8", "#c9a96e", "#2d6a4f"],
    storage: ["128GB", "256GB", "512GB", "1TB"],
    badge: null,
    inStock: true,
    description:
      "Pro camera system with 48MP Fusion camera. A18 Pro chip, titanium design, and Apple Intelligence.",
    specs: {
      Display: '6.3" Super Retina XDR OLED',
      Processor: "A18 Pro Chip",
      RAM: "8GB",
      Battery: "3582mAh",
      Camera: "48MP Fusion + 48MP Ultra + 12MP Telephoto",
      OS: "iOS 19",
    },
  },
  {
    id: 19,
    name: "OnePlus 13R",
    brand: "oneplus",
    category: "flagship",
    price: 699,
    originalPrice: 799,
    rating: 4.4,
    reviews: 167,
    image: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-13r.jpg",
    colors: ["#2b2d42", "#edf2f4"],
    storage: ["256GB", "512GB"],
    badge: "Great Value",
    inStock: true,
    description:
      "Flagship killer returns. Snapdragon 8 Gen 4, 120Hz display, and 80W SUPERVOOC charging.",
    specs: {
      Display: '6.74" LTPO AMOLED 120Hz',
      Processor: "Snapdragon 8 Gen 4",
      RAM: "12GB",
      Battery: "5500mAh",
      Camera: "50MP Main + 8MP Ultra + 2MP Macro",
      OS: "OxygenOS 15 (Android 15)",
    },
  },
  {
    id: 20,
    name: "Google Pixel 10 Pro XL",
    brand: "google",
    category: "flagship",
    price: 1199,
    originalPrice: 1299,
    rating: 4.6,
    reviews: 134,
    image: "https://images.pexels.com/photos/6472073/pexels-photo-6472073.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop",
    colors: ["#f8f9fa", "#212529", "#1a5b8c"],
    storage: ["128GB", "256GB", "512GB"],
    badge: null,
    inStock: true,
    description:
      "The ultimate Pixel experience. Tensor G5, pro-level camera system, and the best AI features on any phone.",
    specs: {
      Display: '6.8" LTPO OLED 120Hz',
      Processor: "Google Tensor G5",
      RAM: "16GB",
      Battery: "5050mAh",
      Camera: "50MP Main + 48MP Ultra + 48MP Telephoto + 5MP Macro",
      OS: "Android 16",
    },
  },
  {
    id: 21,
    name: "OPPO Reno 15 Pro",
    brand: "oppo",
    category: "midrange",
    price: 549,
    originalPrice: 599,
    rating: 4.3,
    reviews: 98,
    image: "https://fdn2.gsmarena.com/vv/bigpic/oppo-reno15-pro.jpg",
    colors: ["#1e1e2f", "#f5f5f5", "#ff6b6b"],
    storage: ["256GB", "512GB"],
    badge: null,
    inStock: true,
    description:
      "Portrait expert. MediaTek Dimensity 8300, 80W SuperVOOC, and a stunning curved AMOLED display.",
    specs: {
      Display: '6.7" AMOLED 120Hz',
      Processor: "MediaTek Dimensity 8300",
      RAM: "12GB",
      Battery: "4700mAh",
      Camera: "50MP Main + 8MP Ultra + 32MP Telephoto",
      OS: "ColorOS 15 (Android 15)",
    },
  },
  {
    id: 22,
    name: "Vivo V50",
    brand: "vivo",
    category: "midrange",
    price: 449,
    originalPrice: 499,
    rating: 4.2,
    reviews: 76,
    image: "https://fdn2.gsmarena.com/vv/bigpic/vivo-v50.jpg",
    colors: ["#1a1a2e", "#f0f0f0", "#e17055"],
    storage: ["128GB", "256GB"],
    badge: null,
    inStock: true,
    description:
      "ZEISS portrait camera system. Ultra-slim design with a massive battery and fast charging.",
    specs: {
      Display: '6.78" AMOLED 120Hz',
      Processor: "Snapdragon 7 Gen 3",
      RAM: "8GB",
      Battery: "5000mAh",
      Camera: "50MP ZEISS Main + 8MP Ultra",
      OS: "Funtouch OS 15 (Android 15)",
    },
  },
  {
    id: 23,
    name: "Samsung Galaxy Z Flip 7",
    brand: "samsung",
    category: "foldable",
    price: 1299,
    originalPrice: 1399,
    rating: 4.3,
    reviews: 64,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip7.jpg",
    colors: ["#2d3436", "#dfe6e9", "#6c5ce7", "#e17055"],
    storage: ["256GB", "512GB"],
    badge: "Compact Fold",
    inStock: true,
    description:
      "Compact foldable with FlexWindow. Snapdragon 8 Gen 4, improved hinge, and Galaxy AI on the go.",
    specs: {
      Display: '6.7" Foldable Dynamic AMOLED + 3.4" Cover',
      Processor: "Snapdragon 8 Gen 4",
      RAM: "12GB",
      Battery: "4000mAh",
      Camera: "50MP Main + 12MP Ultra",
      OS: "One UI 7 (Android 15)",
    },
  },
  {
    id: 24,
    name: "Nothing Phone (3a) Plus",
    brand: "nothing",
    category: "midrange",
    price: 499,
    originalPrice: 549,
    rating: 4.2,
    reviews: 52,
    image: "https://images.pexels.com/photos/2385478/pexels-photo-2385478.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop",
    colors: ["#ffffff", "#000000"],
    storage: ["128GB", "256GB"],
    badge: null,
    inStock: true,
    description:
      "More Glyph, more power. Enhanced LED interface, improved cameras, and clean Nothing OS experience.",
    specs: {
      Display: '6.7" AMOLED 120Hz',
      Processor: "Snapdragon 7s Gen 3",
      RAM: "12GB",
      Battery: "5000mAh",
      Camera: "50MP Main + 50MP Ultra + 50MP Telephoto",
      OS: "Nothing OS 3.5 (Android 15)",
    },
  },
  {
    id: 25,
    name: "Xiaomi Redmi Note 15",
    brand: "xiaomi",
    category: "midrange",
    price: 279,
    originalPrice: 329,
    rating: 4.1,
    reviews: 423,
    image: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-15-5g.jpg",
    colors: ["#2b2d42", "#edf2f4", "#e63946", "#52b788"],
    storage: ["128GB", "256GB"],
    badge: "Budget King",
    inStock: true,
    description:
      "108MP camera, 120Hz AMOLED, and 5000mAh battery. The best budget phone just got better.",
    specs: {
      Display: '6.67" AMOLED 120Hz',
      Processor: "MediaTek Dimensity 7200",
      RAM: "8GB",
      Battery: "5000mAh",
      Camera: "108MP Main + 8MP Ultra + 2MP Macro",
      OS: "HyperOS 2 (Android 15)",
    },
  },
  {
    id: 26,
    name: "Samsung Galaxy A36",
    brand: "samsung",
    category: "midrange",
    price: 399,
    originalPrice: 449,
    rating: 4.2,
    reviews: 198,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a36.jpg",
    colors: ["#2d3436", "#dfe6e9", "#6c5ce7", "#e17055", "#52b788"],
    storage: ["128GB", "256GB"],
    badge: null,
    inStock: true,
    description:
      "Awesome intelligence for all. Galaxy AI features, vibrant Super AMOLED display, and long-lasting battery.",
    specs: {
      Display: '6.6" Super AMOLED 120Hz',
      Processor: "Exynos 1480",
      RAM: "8GB",
      Battery: "5000mAh",
      Camera: "50MP Main + 12MP Ultra + 5MP Macro",
      OS: "One UI 7 (Android 15)",
    },
  },
  {
    id: 27,
    name: "iPhone 16e",
    brand: "apple",
    category: "budget",
    price: 599,
    originalPrice: 649,
    rating: 4.4,
    reviews: 167,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16e.jpg",
    colors: ["#1a1a2e", "#e8e8e8", "#e63946"],
    storage: ["128GB", "256GB"],
    badge: "Affordable",
    inStock: true,
    description:
      "The most affordable iPhone. A18 chip, 48MP camera, and all-day battery in a beautiful design.",
    specs: {
      Display: '6.1" Super Retina XDR OLED',
      Processor: "A18 Chip",
      RAM: "6GB",
      Battery: "3279mAh",
      Camera: "48MP Main + 12MP Ultra",
      OS: "iOS 19",
    },
  },
  {
    id: 28,
    name: "Samsung Galaxy F55",
    brand: "samsung",
    category: "budget",
    price: 329,
    originalPrice: 379,
    rating: 4.0,
    reviews: 256,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f55.jpg",
    colors: ["#2d3436", "#dfe6e9"],
    storage: ["128GB"],
    badge: null,
    inStock: true,
    description:
      "Massive 6000mAh battery with 120Hz Super AMOLED. Reliable performance for everyday use.",
    specs: {
      Display: '6.7" Super AMOLED 120Hz',
      Processor: "Exynos 1480",
      RAM: "8GB",
      Battery: "6000mAh",
      Camera: "50MP Main + 8MP Ultra + 2MP Macro",
      OS: "One UI 7 (Android 15)",
    },
  },
];

export const reviews = [
  {
    id: 1,
    name: "Alex Chen",
    avatar: "AC",
    rating: 5,
    text: "Amazing phone! The camera quality is incredible and the battery lasts all day. Best purchase I've made this year.",
    product: "iPhone 16 Pro Max",
    date: "2 weeks ago",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    avatar: "SJ",
    rating: 5,
    text: "Upgraded from the S24 and the difference is night and day. The AI features are genuinely useful, not just gimmicks.",
    product: "Samsung Galaxy S25 Ultra",
    date: "1 month ago",
  },
  {
    id: 3,
    name: "Mike Rivera",
    avatar: "MR",
    rating: 4,
    text: "Great value for money. The display is gorgeous and the performance is smooth. Only wish the camera was slightly better in low light.",
    product: "OnePlus 13",
    date: "3 weeks ago",
  },
  {
    id: 4,
    name: "Emily Zhang",
    avatar: "EZ",
    rating: 5,
    text: "The Pixel AI is mind-blowing. Photo editing features alone are worth the upgrade. Google really nailed it this year.",
    product: "Google Pixel 10 Pro",
    date: "5 days ago",
  },
  {
    id: 5,
    name: "David Park",
    avatar: "DP",
    rating: 4,
    text: "Best mid-range phone available. Fast charging is a game changer and the camera punches way above its weight class.",
    product: "Redmi Note 15 Pro",
    date: "1 week ago",
  },
  {
    id: 6,
    name: "Lisa Thompson",
    avatar: "LT",
    rating: 5,
    text: "The Glyph interface is so much fun! Battery life is great and the software experience is clean and fast. Highly recommend.",
    product: "Nothing Phone (3)",
    date: "2 weeks ago",
  },
  {
    id: 7,
    name: "James Wilson",
    avatar: "JW",
    rating: 5,
    text: "The Galaxy S25 is the perfect size flagship. Doesn't compromise on performance despite being compact. Love it!",
    product: "Samsung Galaxy S25",
    date: "1 week ago",
  },
  {
    id: 8,
    name: "Maria Garcia",
    avatar: "MG",
    rating: 4,
    text: "iPhone 16 Pro is a solid upgrade. The camera is phenomenal and the battery finally lasts two days. Titanium feels premium.",
    product: "iPhone 16 Pro",
    date: "3 days ago",
  },
  {
    id: 9,
    name: "Kevin Zhang",
    avatar: "KZ",
    rating: 4,
    text: "Great foldable at a reasonable price. The Flip 7 improved battery life and the cover screen is actually useful now.",
    product: "Samsung Galaxy Z Flip 7",
    date: "2 weeks ago",
  },
];
